# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
