# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_classes.CarClass')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
